version: '3'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "80:8069"
    #tty: true
    #command: -- --dev=reload

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./varlogodoo:/var/log/odoo
      - ./addons_propios:/mnt/extra-addons
      - ./addons_terceros:/mnt/third-addons
      - ./oca/account-analytic:/mnt/oca
      
  db:
    image: postgres:12
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=crsJVA!_02
      - POSTGRES_USER=odoo14c
      - PGDATA=/var/lib/postgresql/data/pgdata1
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata1
volumes:
  odoo-web-data:
  odoo-db-data:
